### ISSUE TITLE
Look at this:

### ISSUE THREAD

**Issue by username1565** [zxing-js/text-encoding#2]
![ecstatic](https://user-images.githubusercontent.com/39200328/81806948-de0ddb00-9525-11ea-8974-605980c51ff8.PNG)

https://github.com/zxing-js/text-encoding/blob/21ba9edef4dc41f2409b8cc0134570fb76e34320/yarn.lock#L1254-L1262

**Comment by odahcam** [comment]
I just gonna close it since it's outdated. Thanks.

**Comment by username1565** [comment]
This is not outdated.
This warning you can see when you be the owner of repositary, not when you fork it.
For example, you can create new repositary, upload all files, and see this warning.
Some vulnerability there need to fix, and maybe, will be better to use another version of `ecstatic` or something else, instead of this.
