### ISSUE TITLE
NPM package removed

### ISSUE THREAD

**Issue by Exagone313** [zxing-js/text-encoding#9]
Hello,

I don't know if this is intended, but the NPM package is no longer accessible (it returns a 404 error).

It is an `optionalDependencies` for `web-encoding`, which is a dependency for `minio`.

Issue related: https://github.com/Gozala/web-encoding/issues/33

Is it possible to bring back the package?

Thank you.

**Comment by VictorGlindasPaf** [comment]
`web-encoding` is also a dependency on `@mswjs/interceptors`, which breaks our install now that this package is no longer available: 😕

**Comment by Exagone313** [comment]
This may be related, or may impact the resolution of the issue, but NPM is currently down: https://status.npmjs.org/incidents/drj38qn6qm59

**Comment by leidsoncruz** [comment]
I think it is related to the NPM incident. We are facing the same issue with this package and others. However, it's an intermittent problem.

https://status.npmjs.org/

**Comment by VictorGlindasPaf** [comment]
Yeah, seems to resolve itself when NPM is working again, thanks!
